name: Setup with NPM
description: Perform standard setup and install dependencies using npm
inputs:
  node-version:
    description: The version of Node.js to install
    default: 22.x

runs:
  using: composite
  steps:
    - name: Set Node.js (${{ inputs.node-version }})
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs['node-version'] }}
        cache: npm
        cache-dependency-path: package-lock.json
    - name: Install dependencies
      shell: bash
      run: |
        if [ -f package-lock.json ]; then
          npm ci --silent
        else
          npm install --silent
        fi
